<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '68d5572f5b94fb85b83d394917714ea4',
  'DATABASE_URL' => 'mysql://access:@127.0.0.1:3306/db_project?serverVersion=5.7',
);
